{{- $domain := .Values.exposes.domain }}
{{- $issuer := .Values.exposes.issuer }}
{{- range .Values.exposes.ingresses }}
{{- if .createCert }}
{{- $name := .name }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
  name: {{ $name }}.{{ $domain }}
spec:
  dnsNames:
  - {{ $name }}.{{ $domain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ $issuer }}
  secretName: {{ $name }}-cert
{{- end }}
{{- end }}