apiVersion: v2
name: helm-loki
version: 1.1.0-rc2
appVersion: 1.16.0
description: A Helm chart wrapper for Loki

dependencies:
  - name: loki-stack
    version: "2.4.1"
    repository: "https://grafana.github.io/helm-charts/"
    condition: loki-stack.enabled

  - name: loki-distributed
    version: "0.35.0"
    repository: "https://grafana.github.io/helm-charts/"
    condition: loki-distributed.enabled

  - name: promtail
    version: "3.6.0"
    repository: "https://grafana.github.io/helm-charts//"
    condition: promtail.enabled

  - name: grafana
    version: "4.0.0"
    repository: "https://grafana.github.io/helm-charts/"
    condition: grafana.enabled    
