apiVersion: v2
name: helm-loki
version: 1.1.12-rc1
appVersion: 1.23.0
description: A Helm chart wrapper for Loki

dependencies:
  - name: loki-stack
    version: "2.6.4"
    repository: "https://grafana.github.io/helm-charts/"
    condition: loki-stack.enabled

  - name: loki-distributed
    version: "0.48.4"
    repository: "https://grafana.github.io/helm-charts/"
    condition: loki-distributed.enabled

  - name: promtail
    version: "5.1.0"
    repository: "https://grafana.github.io/helm-charts/"
    condition: promtail.enabled

  - name: grafana
    version: "6.29.6"
    repository: "https://grafana.github.io/helm-charts/"
    condition: grafana.enabled    

  - name: fluent-bit
    alias: fluentbit
    version: "0.20.4"
    repository: "https://fluent.github.io/helm-charts"
    condition: fluentbit.enabled
